name: smoke_test

on:
  push:
  pull_request:

jobs:
  smoke_test_ubuntu:
    uses: cosmtrek/air/.github/workflows/smoke_test_reuse_job.yml@master
    with:
      run_on: ubuntu-latest
  smoke_test_macos:
    uses: cosmtrek/air/.github/workflows/smoke_test_reuse_job.yml@master
    with:
      run_on: macos-latest
  smoke_test_windows:
    uses: cosmtrek/air/.github/workflows/smoke_test_window_reuse_job.yml@master
    with:
      run_on: windows-latest